routes/dashboard.py
from flask import Blueprint, render_template,session,redirect,request,jsonify
from model.models import *
from datetime import datetime
from sqlalchemy import cast, func,Integer,text
import json
dashboard_bp = Blueprint('dashboard', __name__)

@dashboard_bp.route('/dashboard')
def dashboard():
      return render_template('dashboard.html')
@dashboard_bp.route('/log/get-list', methods=['GET'])
def getEmpLogList():    
      query = db.session.query(
        Employees_log.id,
        Employees_log.employee_number,
        Employees.name.label('employee_name'),
        Employees.gender.label('employee_gender'),
        Employees_log.building,
        Employees_log.floor,
        Employees_log.station,
        Buildings.building_name,
        Floors.floor_name,
        Stations.station_name,
        Employees_log.log_date_time,
        Employees_log.status,
        Employees_log.shift,       
        Employees_log.objects       
    ).join(Employees, Employees_log.employee_number == Employees.employee_number)\
     .join(Buildings, cast(Employees_log.building, Integer) == Buildings.id)\
     .join(Floors, cast(Employees_log.floor, Integer) == Floors.id)\
     .join(Stations, cast(Employees_log.station, Integer) == Stations.id)
    
      role = session.get('role')
      logged_user = session.get('logged_user') 
      
      today = datetime.today().date()   
      total_query = query.filter(Employees_log.log_date_time.like(f'{today} %'))
      in_total_query = query.filter(Employees_log.log_date_time.like(f'{today} %'),Employees_log.status=='in')
      out_total_query = query.filter(Employees_log.log_date_time.like(f'{today} %'),Employees_log.status=='out')

      if role!="admin":
          in_total_query = in_total_query.filter(Employees_log.created_by==logged_user )
          out_total_query = out_total_query.filter(Employees_log.created_by==logged_user)
          
     
      total_records= total_query.count()  
      total_records_in = in_total_query.count()
      total_records_out= out_total_query.count()

      logData = {
        "total_records": total_records,   
        "in": total_records_in,                      
        "out": total_records_out,     
                 
    }

      return jsonify(logData)

def prepare_logs(result):
    shift_mapping = {
        'S1': 'Shift 1',
        'S2': 'Shift 2',
        'S3': 'Shift 3',
        'S4': 'Shift 4'
    }
    body_parts = {bp.id: bp.body_parts_name for bp in Bodyparts.query.all()}
    objects = {obj.id: obj.object_name for obj in Objectmappings.query.all()}
    logs = []
    
    for log in result:
        shift_full_name = shift_mapping.get(log.shift, log.shift)  # Get shift name or default to original
        try:
            objects_data = json.loads(log.objects)  # Parse the objects JSON
        except (json.JSONDecodeError, TypeError) as e:
            print(f"Error decoding JSON for log {log.id}: {e}")
            objects_data = []  # Set to empty list in case of error
        
        body_part_map = {}

        for item in objects_data:
            body_part_id = item.get('g')  # Get body part ID
            object_ids = item.get('o', '').split(',')  # Split object IDs (comma-separated)
            
            # Strip any extra spaces from object IDs
            object_ids = [obj_id.strip() for obj_id in object_ids if obj_id.strip()]
            
            body_part_name = body_parts.get(body_part_id, "Unknown")
            object_names = [objects.get(int(obj_id), "Unknown") for obj_id in object_ids]

            if body_part_name not in body_part_map:
                body_part_map[body_part_name] = []
            body_part_map[body_part_name].extend(object_names)

        # Build the output for metal exceptions
        body_parts_output = []
        for bp_name, obj_names in body_part_map.items():
            objects_str = ', '.join(sorted(set(obj_names)))  # Use set to avoid duplicates, sorted for consistency
            body_parts_output.append(f"{bp_name}: {objects_str}")

       
        logs.append({
            
            'Building': log.building_name,
            'Floor': log.floor_name,
            'Station': log.station_name,
            'Date_Time': log.log_date_time,
            'Transaction': log.status,
            'EmpID': log.employee_number,
            'EmployeeName': log.employee_name,
            'Gender': log.employee_gender,
            'Shift': shift_full_name,
            'TypeOfMetalExceptions': ' | '.join(body_parts_output)
        })

    return logs

routes/login.py
from flask import Blueprint, render_template,session,redirect,request,url_for,flash
from werkzeug.security import generate_password_hash,check_password_hash
from model.models import *
import logging
login_bp = Blueprint('login', __name__)


@login_bp.route('/login')
def login():
      return render_template('login.html')

@login_bp.route('/')
def index():
     return render_template('login.html')

@login_bp.route("/checklogin",methods=['POST'])
def checklogin():
    user = Users.query.filter_by(username=request.form.get('username'),status='enable').first()
    if user and check_password_hash(user.password, request.form.get('password')):
        user.lastLogin = get_current_time()
        db.session.commit()
        session['logged_user'] = user.id
        session['username'] = user.username
        session['role'] = user.role
        session['rights'] = user.rights
        if user.role=='admin':
            return redirect(url_for('dashboard.dashboard'))
        else:
            return redirect(url_for('login.selectShift'))
    else:
        flash('Invalid username or password.', 'error')
        return redirect(url_for('login.login'))
        

@login_bp.route("/selectShift",methods=['GET'])
def selectShift():
    if session['username']:
        session['shift'] = request.form.get('shift')
        session['building'] = request.form.get('building')
        session['floor'] = request.form.get('floor')
        session['station'] = request.form.get('station')
        logging.warning(f"Session contents: {session}")
        return render_template('shift_selection.html')
    else:
         return redirect(url_for('login.login'))

@login_bp.route("/setShift",methods=['POST'])
def setShift():
    if session['username']:
        session['shift'] = request.form.get('shift')
        session['building'] = request.form.get('building')
        session['floor'] = request.form.get('floor')
        session['station'] = request.form.get('station')
        logging.warning(f"Session contents: {session}")
        return redirect(url_for('dashboard.dashboard'))
    else:
         return redirect(url_for('login.login'))


@login_bp.route('/logout')
def logout():
    session.pop('username', None)
    session.pop('role', None)
    session.pop('rights', None)
    session.pop('shift', None)
    session.pop('building', None)
    session.pop('floor', None)
    session.pop('station', None)
    return redirect(url_for('login.login'))

routes/logs.py
from flask import Blueprint, render_template,session,redirect,request,jsonify
from model.models import *
from helpers.masters_helper import *
import json

logs_bp = Blueprint('logs', __name__)

@logs_bp.route('/logs')
def logs():
    return render_template('logs.html')
@logs_bp.route('/list-view')
def list_view():
    return render_template('list_view.html')

@logs_bp.route('/logs/get-list',methods=['POST'])
def getLogList():
    limit = request.args.get('length', default=10, type=int)
    offset = request.args.get('start', default=0, type=int)
    
    logs_with_employee_info = db.session.query(
        Employees_log,
        Employees.name,
        Employees.gender,
        Buildings.building_name,
        Floors.floor_name,
        Stations.station_name
    ).join(Employees, Employees.employee_number == Employees_log.employee_number).join(Buildings,Buildings.id==Employees_log.building).join(Floors,Floors.id==Employees_log.floor).join(Stations,Stations.id==Employees_log.station).limit(limit).offset(offset).all()

    results = []
    for log, name, gender,building_name,floor_name,station_name in logs_with_employee_info:
        results.append({
            'log_id': log.id,
            'number': log.employee_number,
            'shift': getShiftById(log.shift),
            'building': building_name,
            'floor': floor_name,
            'status': log.status,
            'station': station_name,
            'log_date_time': log.log_date_time,
            'name': name,
            'gender': gender
        })
    
    userData = {
        "draw": 1,               
        "recordsTotal": 100,    
        "recordsFiltered": 100, 
        "data":results
    }

    return jsonify(userData)

@logs_bp.route('/view-log/',methods=['GET'])
def view_log():
    log_id = request.args.get('id')
    return render_template('scan.html',log_id=log_id)

@logs_bp.route("/get-log-details")
def get_log_details():
    log_id = request.args.get('id')
    result = db.session.query(Employees_log, Employees).join(
        Employees, Employees.employee_number == Employees_log.employee_number
    ).filter(Employees_log.id == log_id).first()
    employee_log, employee = result
    bObjects = []
    objects = json.loads(employee_log.objects)
    # print(objects)
    # if isinstance(objects, dict):
    #     print('yesd')
    if isinstance(objects, list):
        #print('yesl')
        for item in objects:
            id_list = [int(id.strip()) for id in item['o'].split(',')]
            results = Objectmappings.query.filter(Objectmappings.id.in_(id_list)).all()
            object_names = [obj.object_name for obj in results]
            object_names_str = ', '.join(object_names)
            bObjects.append({'p':item['p'],'g':getBodyPartsById(item['g']),'o':object_names_str})
            
    result = {
            "log_id": employee_log.id,
            "employee_number": employee_log.employee_number,
            "points": employee_log.points,
            "objects": employee_log.objects,
            "log_date_time": employee_log.log_date_time,
            "employee_name": employee.name,
            "employee_gender": employee.gender,
            "image":employee.image,
            'bObjects':bObjects,
            'shift':getShiftById(employee_log.shift),
            'building':getBuildingNameById(employee_log.building),
            'floor':getFloorNameById(employee_log.floor),
            'station':getStationNameById(employee_log.station),
            'medical_implants':employee.medical_implants,
            'medical_implants_position':employee.medical_implants_position,
            
        }
    return jsonify(result)

routes/scan.py
from flask import Blueprint, render_template,session,redirect,request,jsonify,url_for
from sqlalchemy import text,func, or_
from sqlalchemy.dialects.postgresql import array

from model.models import *
from helpers.masters_helper import *
import re
import random
import string
import pytesseract
import os
from PIL import Image
scan_bp = Blueprint('scan', __name__)

def generate_random_filename(length=10, extension='txt'):
    # Generate random letters and digits
    characters = string.ascii_letters + string.digits
    random_name = ''.join(random.choice(characters) for _ in range(length))
    return f"{random_name}.{extension}"


@scan_bp.route('/get_o_values')
def get_o_values():
    # Define your raw SQL query
    raw_query = text("""
        SELECT EL.* FROM (SELECT
            json_array_elements(objects::json) ->> 'o' AS o_values
        FROM employees_log) AS EL WHERE NOT ('2' = ANY (string_to_array(o_values, ','))) 
    """
    )
    
    # Execute the raw SQL query
    result = db.session.execute(raw_query).mappings()
    
    r = ''
    # Fetch all results
    o_values = [row['o_values'] for row in result]

    return {"o_values": o_values}

@scan_bp.route('/get_o_values1')
def get_o_values1():
   

    subquery = db.session.query(
        Employees_log.log_date_time,
        Employees_log.building,
        func.json_array_elements_text(Employees_log.objects.cast(db.JSON)).label('o_values')
    ).filter(
        Employees_log.building == 2
    ).subquery()

    result = db.session.query(subquery).filter(
        or_(
            ~(func.any(func.string_to_array(subquery.c.o_values, ','))!='2' ),
             func.any(func.string_to_array(subquery.c.o_values, ','))!='4' 
        )
    ).all()
    
    o_values = [row['o_values'] for row in result]

    return {"o_values": o_values}

@scan_bp.route('/scan')
def scan():
    shift_name = getShiftById(session['shift'])
    building_name = getBuildingNameById(session['building'])
    floor_name = getFloorNameById(session['floor'])
    station_name = getStationNameById(session['station'])
    return render_template('scan.html',shift_name=shift_name,building_name=building_name,floor_name=floor_name,station_name=station_name)

@scan_bp.route("/get-log-list",methods=['GET'])
def get_log_list():
    logs_with_employee_info = db.session.query(
        Employees_log,
        Employees.name,
        Employees.gender
    ).join(Employees, Employees.employee_number == Employees_log.employee_number).all()

    results = []
    for log, name, gender in logs_with_employee_info:
        results.append({
            'log_id': log.id,
            'employee_number': log.employee_number,
            'log_date_time': log.log_date_time,
            'employee_name': name,
            'employee_gender': gender
        })

    return jsonify(results)

@scan_bp.route('/saveData',methods=['POST'])
def saveData():
    current_time = datetime.now()
    current_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
    
    Employees.query.filter_by(employee_number=request.form.get('emp_number')).update({"gender":request.form.get('gender'),"medical_implants":request.form.get('medical_implants'),"medical_implants_position":request.form.get("medical_implants_position")})
    db.session.commit()
    newLog = Employees_log(employee_number=request.form.get('emp_number'),points=request.form.get('points'),objects=request.form.get('object'),log_date_time=current_time,status=request.form.get('status'),shift=request.form.get('shift'),building=request.form.get('building'),floor=request.form.get('floor'),station=request.form.get('station'),object_ids=request.form.get('object_ids'),created_by=session['logged_user'])
    db.session.add(newLog)
    db.session.commit()
    return {"status":"ok","msg":"Saved successfully"}


@scan_bp.route('/upload', methods=['POST'])
def upload_image():
    
    if 'image' not in request.files:
        return redirect(url_for('index'))

    image_file = request.files['image']
    if image_file.filename == '':
        return redirect(url_for('index'))
    
    image_file.filename = generate_random_filename(15, 'jpg')
    # Save the uploaded image to a temporary location
    image_path = os.path.join('static/uploads', image_file.filename)
    image_file.save(image_path)
    
    
    image = Image.open(image_path)
    text = pytesseract.image_to_string(image)
    
    print(text)
    match = re.search(r'Employee Number:\s*(\d+)', text)
    gender =""
        
    employee_number = ""
    emp_name = ""
    medical_implants = [];
    medical_implants_position = [];
    if match:
        employee_number = match.group(1)
        ("Employee Number:", employee_number)
        
        if employee_number!="":
            employee = Employees.query.filter_by(employee_number=employee_number).first()

            if employee:
                gender = employee.gender
                emp_name = employee.name
                medical_implants = employee.medical_implants
                medical_implants_position = employee.medical_implants_position
                #if os.path.exists(image_path):
                    #os.remove(image_path)
            else:
                textArr = text.split('\n')
                cleaned_textArr = [item for item in textArr if item.strip()]
                pattern = r'Employee Number'
                index = -1
                for i, item in enumerate(cleaned_textArr):
                    if re.search(pattern, item):  # Use re.search to check for a match
                        index = i
                        break
                if index==0:
                     os.remove(image_path)
                     return {"status":"failed","msg":"Can't read the name from id card"}
                
                if index>=1:
                    nameIdx = index-1
                    emp_name = cleaned_textArr[nameIdx].replace("-","")
                
                gender = request.form.get('gender')
                if os.path.exists(image_path):
                    old_img_path = image_path
                    os.rename(image_path, 'static/uploads/'+employee_number+'.jpg')                    
                newEmployee = Employees(name=emp_name, employee_number=employee_number,gender=gender,image=employee_number+'.jpg',created_by=session['logged_user'])
                db.session.add(newEmployee)
                db.session.commit()
            
            return {"status":"ok","msg":"Processed successfully","emp_number":employee_number,"emp_name":emp_name,"emp_gender":gender,"medical_implants":medical_implants,"medical_implants_position":medical_implants_position}
        
        else:
            return {"status":"failed","msg":"Processed successfully","emp_number":employee_number}
    
    else:
       if os.path.exists(image_path):
        os.remove(image_path)
       return {"status":"failed","msg":"Can't read the id card , scan again"}
   

templates/base.html
{% include 'header.html' %}
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
{% block javascripts %}{% endblock %}
</body>
</html>

templates/camera_test.html
<!DOCTYPE html>
<html>
<head>
    <title>Access Mobile Back Camera</title>
</head>
<body>
    <video id="video" width="320" height="240" autoplay></video>

    <script>
        async function startCamera() {
            try {
                const stream = await navigator.mediaDevices.getUserMedia({
                    video: {
                        facingMode: 'environment' // This specifies the back camera
                    }
                });
                const videoElement = document.getElementById('video');
                videoElement.srcObject = stream;
            } catch (err) {
                console.error('Error accessing camera: ', err);
            }
        }

        startCamera();
    </script>
</body>
</html>

templates/footer.html
<script src="{{ url_for('static', filename='js/vendor.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>

templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="description" />
    <script src="{{ url_for('static', filename='js/config.js') }}"></script>
    <link href="{{ url_for('static', filename='css/vendor.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='css/app.min.css') }}" rel="stylesheet" type="text/css" id="app-style" />
    <link href="{{ url_for('static', filename='css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='css/dataTables.dataTables.min.css') }}" rel="stylesheet" type="text/css">
    
</head>

<body>
    <div class="wrapper">
        <div class="sidenav-menu">
            <!-- <a href="index.html" class="logo">
                <span class="logo-light">
                    <span class="logo-lg"><img style="height: 40px;" src="{{request.root}}static/images/logo.png" alt="logo"></span>
                    <span class="logo-sm"><img style="height: 30px;" src="{{request.root}}static/images/logo-sm.png" alt="small logo"></span>
                </span>
                <span class="logo-dark">
                    <span class="logo-lg"><img style="height: 40px;" src="{{request.root}}static/images/logo-dark.png" alt="dark logo"></span>
                    <span class="logo-sm"><img style="height: 30px;" src="{{request.root}}static/images/logo-sm.png" alt="small logo"></span>
                </span>
            </a> -->
            <button class="button-sm-hover">
                <i class="ti ti-circle align-middle"></i>
            </button>
            <button class="button-close-fullsidebar">
                <i class="ti ti-x align-middle"></i>
            </button>
            <div data-simplebar style="border-top:1px solid rgba(0,0,0,0.1) ;">
                <ul class="side-nav">
                    <li class="side-nav-title mt-2">Menu</li>
                       <li class="side-nav-item">
                        <a href="{{url_for('dashboard.dashboard')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-layout-dashboard"></i></i></span>
                            <span class="menu-text"> Dashboard </span>
                        </a>
                    </li>
                    {% if session['role']!='admin' %}
                    <li class="side-nav-item">
                        <a href="{{url_for('scan.scan')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-body-scan"></i></span>
                            <span class="menu-text"> Scan </span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="side-nav-item">
                        <a href="{{url_for('users.users')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-user"></i></span>
                            <span class="menu-text"> Users </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a href="{{url_for('masters.masters')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-list-details"></i></span>
                            <span class="menu-text"> Master </span>
                        </a>
                    </li>
                      <li class="side-nav-item">
                        <a href="{{url_for('parts.parts')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-man"></i></span>
                            <span class="menu-text"> Body parts </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a href="{{url_for('logs.logs')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-file-invoice"></i></span>
                            <span class="menu-text"> Logs </span>
                        </a>
                    </li>
                     {% if session['rights']=='R' %}
                    <li class="side-nav-item">
                        <a href="{{url_for('reports.reports')}}" class="side-nav-link">
                            <span class="menu-icon"><i class="ti ti-report"></i></span>
                            <span class="menu-text"> Reports </span>
                        </a>
                    </li>
                     {% endif %}
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
        <header class="app-topbar">
            <div class="page-container topbar-menu">
                <div class="d-flex align-items-center gap-2">
                    <a href="index.html" class="logo">
                        <span class="logo-light">
                            <span class="logo-lg"><img src="{{ url_for('static', filename='images/logo.png') }}" alt="logo"></span>
                            <span class="logo-sm"><img src="{{ url_for('static', filename='images/logo-sm.png') }}" alt="small logo"></span>
                        </span>
                        <span class="logo-dark">
                            <span class="logo-lg"><img src="{{ url_for('static', filename='images/logo-dark.png') }}" alt="dark logo"></span>
                            <span class="logo-sm"><img src="{{ url_for('static', filename='images/logo-sm.png') }}" alt="small logo"></span>
                        </span>
                    </a>
                    <button class="sidenav-toggle-button px-2">
                        <i class="ti ti-menu-deep fs-24"></i>
                    </button>
                    <button class="topnav-toggle-button px-2" data-bs-toggle="collapse"
                        data-bs-target="#topnav-menu-content">
                        <i class="ti ti-menu-deep fs-22"></i>
                    </button>
                </div>
                <div class="d-flex align-items-center gap-2">
                    <div class="topbar-item d-none d-sm-flex">
                        <button class="topbar-link" id="light-dark-mode" type="button">
                            <i class="ti ti-moon fs-22"></i>
                        </button>
                    </div>
                    <div class="topbar-item nav-user">
                        <div class="dropdown">
                            <a class="topbar-link dropdown-toggle drop-arrow-none px-2" data-bs-toggle="dropdown"
                                data-bs-offset="0,19" type="button" aria-haspopup="false" aria-expanded="false">
                                <img src="{{ url_for('static', filename='images/user.png') }}" width="32" class="rounded-circle me-lg-2 d-flex" alt="user-image">

                                <span class="d-lg-flex flex-column gap-1 d-none">
                                    <h5 class="my-0">{{ session['username'] }}</h5>
                                    <h6 class="my-0 fw-normal">{{ session['role'] }}</h6>
                                </span>
                                <i class="ti ti-chevron-down d-none d-lg-block align-middle ms-2"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end">
                                <div class="dropdown-header noti-title">
                                    <h6 class="text-overflow m-0">Welcome !</h6>
                                </div>
                                <a href="javascript:void(0);" class="dropdown-item">
                                    <i class="ti ti-user-hexagon me-1 fs-17 align-middle"></i>
                                    <span class="align-middle">My Account</span>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item">
                                    <i class="ti ti-settings me-1 fs-17 align-middle"></i>
                                    <span class="align-middle">Change Password</span>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a href="{{url_for('login.logout')}}" class="dropdown-item active fw-semibold text-danger">
                                    <i class="ti ti-logout me-1 fs-17 align-middle"></i>
                                    <span class="align-middle">Sign Out</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Log In</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <script src="{{request.root}}static/js/config.js"></script>
    <link href="{{request.root}}static/css/vendor.min.css" rel="stylesheet" type="text/css" />
    <link href="{{request.root}}static/css/app.min.css" rel="stylesheet" type="text/css" id="app-style" />
</head>

<body>
    <div class="auth-bg d-flex min-vh-100 justify-content-center align-items-center">
        <div class="row g-0 justify-content-center w-100 m-xxl-5 px-xxl-4 m-3">
            <div class="col-xl-4 col-lg-5 col-md-6">
                <div class="card overflow-hidden text-center h-100 p-xxl-4 p-3 mb-0">
                    <a href="index.html" class="auth-brand mb-3">
                      
                    </a>

                    <h3 class="fw-semibold mb-2">Login your account</h3>
                    {% with messages = get_flashed_messages(with_categories=True) %}
                        {% if messages %}
                            <div class="alert alert-danger">
                            {% for category, message in messages %}
                                {{ message }}
                            {% endfor %}
                            </div>
                        {% endif %}
                        {% endwith %}
                    <form action="{{url_for('login.checklogin')}}" method="post" class="text-start mb-2 mt-3">
                        <div class="mb-3">
                            <label class="form-label">Username</label>
                            <input type="text" name="username" class="form-control" placeholder="Enter your username" value="" required>
                        </div>

                        <div class="mb-3">
                            <label class="form-label" for="example-password">Password</label>
                            <input type="password" id="example-password" class="form-control"
                                placeholder="Enter your password" name="password" value="" required>
                        </div>

                        <div class="d-flex justify-content-between mb-3">
                            <!-- <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="checkbox-signin">
                                <label class="form-check-label" for="checkbox-signin">Remember me</label>
                            </div>

                            <a href="#" class="text-muted border-bottom border-dashed">Forget Password</a> -->
                        </div>

                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">Login</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>
    <script src="{{request.root}}static/js/vendor.min.js"></script>
    <script src="{{request.root}}static/js/app.js"></script>
</body>
</html>